config/routes.rb
Rails.application.routes.draw do

  #errrs routes
  match "/404", :to => "errors#error_404", :via => :all
  match "/500", :to => "errors#error_500", :via => :all
  match "/422", :to => "errors#error_422", :via => :all

  #routes for Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  authenticated :user do
      #routes for root AUTHENTICATED
      get '/', :to => 'home#index', as:'home'
  end


  #routes for root NOT AUTHENTICATED
  root 'home#splash'

  #routes that require authentication
  authenticated do

    #routes for resources
    resources :matches #, except: [:index]
    resources :free_matches #, except: [:index]
    resources :teams #, except: [:index]
    resources :users, only: [:show]
    resources :notifications do
      collection do
        post :mark_as_read
      end
    end


    # routes for my autocomplete via Ajax
    get '/autocomplete/:q', :to => 'searches#autocomplete_users',as:'autocomplete_users'

    # routes for the searches
    get '/search', :to =>'searches#search',as: 'search'

    #routes for model User
    match 'users/:id' => 'users#show', via: :get
    match 'users/:id/settings' => 'users#settings', via: :get, as: 'user_settings'
    get 'users/:id' => 'users#show'
    get 'users/:id/set_soccer_role', :to =>'users#set_soccer_role', as: 'set_soccer_role'
    post 'users/:id/set_soccer_role', :to =>'users#update_soccer_role', as: 'update_soccer_role'
    get 'users/:id/matches_info', :to =>'users#matches_info', as: 'matches_info'

    #routes for model Team
    get 'teams/:id/edit_members_roles', :to => 'teams#edit_members_roles', as: 'edit_members_roles'
    post 'teams/:id/update_members_roles', :to => 'teams#update_members_roles', as: 'update_members_roles'
    get 'teams/:id/select_new_players', :to => 'teams#select_new_players', as: 'select_new_players'
    post 'teams/:id/invite', :to => 'teams#invite', as: 'invite'
    post 'teams/:id/add_player', :to => 'teams#add_player', as: 'add_team_player'

    #routes for model Match
    get '/new_match_set_type', :to => 'matches#new_set_type', as:'new_match_set_type'
    post 'matches/:id/set_match_scores', :to =>'matches#set_match_scores', as: 'set_match_scores'
    post 'matches/:id/accept_team_request', :to => 'matches#accept_request', as: 'accept_match_request'
    get 'matches/:id/set_score', :to => 'matches#set_score', as: 'set_match_score'
    post 'matches/:id/update_score', :to => 'matches#update_score', as: 'update_match_score'

    #routes for model FreeMatch
    post 'free_match/:id/add_player', :to => 'free_matches#add_player', as: 'add_free_match_player'
    post 'free_matches/:id/request', :to => 'free_matches#request_free_match', as: 'request_free_match'
    post 'free_matches/:id/accept_request/:uid', :to => 'free_matches#accept_request', as: 'accept_free_match_request'

    #routes to Follow/Unfollow via Ajax
    get '/follow/:following_id/:follower_id', :to => 'users#follow', as: 'follow'
    get '/unfollow/:following_id/:follower_id', :to => 'users#unfollow', as: 'unfollow'

  end
end

app/models/free_match.rb
class FreeMatch < ApplicationRecord
  resourcify
  has_and_belongs_to_many :users
end

app/controllers/free_matches_controller.rb
class FreeMatchesController < ApplicationController
  before_action :set_free_match, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! #-> routes to the login / signup if not authenticated

  # GET /free_matches
  # GET /free_matches.json
  def index
    #@free_matches = FreeMatch.all
    #@user = current_user
    redirect_to root_path
  end

  # GET /free_matches/1
  # GET /free_matches/1.json
  def show
    @free_match = FreeMatch.find(params[:id])
  end

  # GET /free_matches/new
  def new
    @users_to_invite = User.where('id != ?', current_user.id)
    @free_match = FreeMatch.new
  end

  # GET /free_matches/1/edit
  def edit
    @users_to_invite = User.where('id != ?', current_user.id)
    @free_match = FreeMatch.find(params[:id])
    @free_march_users = @free_match.users
    if !current_user.has_role?(:manager, @free_match)
      return redirect_to("/free_matches")
    end
  end

  # POST /free_matches
  # POST /free_matches.json
  def create
    @free_match = FreeMatch.new(free_match_params)
    @user = current_user
    respond_to do |format|
      if @free_match.save
        free_match = @free_match
        Activity.create(actor: current_user, action: "created",object: free_match)
        current_user.free_matches << @free_match
        current_user.add_role(:manager, @match)
        params[:player_to_add].each do |email|
          user = User.where(email: email).first
          if user.present? && Notification.where(recipient: user, actor: current_user, action: "invited",notifiable: free_match).empty? == true
            free_match = @free_match
            Notification.create(recipient: user, actor: current_user, action: "invited",notifiable: free_match)
          end
        end

        format.html { redirect_to @free_match, notice: 'Free match was successfully created.' }
        format.json { render :show, status: :created, location: @free_match }
      else
        format.html { render :new }
        format.json { render json: @free_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /free_matches/1
  # PATCH/PUT /free_matches/1.json
  def update
    if user_signed_in? && current_user.has_role?(:manager, @free_match)
      params[:player_to_add].each do |email|
        user = User.where(email: email).first
        if user.present? && Notification.where(recipient: user, actor: current_user, action: "invited",notifiable: free_match).empty? == true
          free_match = @free_match
          Notification.create(recipient: user, actor: current_user, action: "invited",notifiable: free_match)
        end
      end
    end
    respond_to do |format|
      if @free_match.update(free_match_params)
        format.html { redirect_to @free_match, notice: 'Free match was successfully updated.' }
        format.json { render :show, status: :ok, location: @free_match }
      else
        format.html { render :edit }
        format.json { render json: @free_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /free_matches/1
  # DELETE /free_matches/1.json
  def destroy
    Notification.where(notifiable:@free_match).each do |notification|
      notification.delete
    end
    Activity.where(object:@free_match).each do |activity|
      activity.delete
    end
    @free_match.users.each do |user|
      if user.has_role?(:manager, @free_match)
        user.remove_role(:manager,@free_match)
      end
      if user.has_role?(:member, @free_match)
        user.remove_role(:member,@free_match)
      end
    end
    @free_match.delete
    respond_to do |format|
      format.html { redirect_to free_matches_url, notice: 'Free match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_player
    @free_match = FreeMatch.find(params[:id])
    if Notification.where(recipient: current_user, notifiable: @free_match, action:"invited").present?
      @free_match.users << current_user
      current_user.add_role :member, @free_match
      Notification.where(action:"invited",notifiable:@free_match,recipient:current_user).first.delete
      redirect_to free_match_path(@free_match)
    end
  end

  def accept_request
    @free_match = FreeMatch.find(params[:id])
    user = User.friendly.find(params[:uid])
    @free_match.users << user
    user.add_role :member, @free_match
    Notification.where(action:"requested",notifiable:@free_match,actor:user).first.delete
    redirect_to free_match_path(@free_match), notice: 'Invito Accettato'
  end

  def request_free_match
    @free_match = FreeMatch.find(params[:id])
    users = User.with_role(:manager,@free_match)
    users.each do |user|
      if Notification.where(
        recipient: user,
        actor:current_user,
        notifiable: @free_match,
        action:"requested").empty?

        free_match = @free_match
        Notification.create(recipient: user, actor: current_user, action: "requested",notifiable: free_match)
        Activity.create(actor: current_user, action: "requested",object: free_match)
      end
    end
    redirect_to root_path, notice: 'Richiesta spedita.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_free_match
      @free_match = FreeMatch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def free_match_params
      #params.fetch(:free_match, {})
      params.require(:free_match).permit(:date, :latitude, :longitude, :player_to_add,:uid,:name)
    end
end

app/helpers/free_matches_helper.rb
module FreeMatchesHelper
end

app/views/free_matches/_form.html.erb
<%= form_with(model: free_match, local: true, html: { id: "free_match_form" }) do |form| %>
  <% if free_match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(free_match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% free_match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :date %>
  <%= form.hidden_field :latitude %>
  <%= form.hidden_field :longitude %>
  <% if @free_march_users.present? && @free_march_users.size > 0 %>
  <% @free_march_users.each do |user| %>
  <input type="hidden" name="player_to_add[]" value"<%=user.id%>"%>
  <% end %>
  <% end %>


      <div class="row">
        <div class="section col s12 m6">
          <h5>Seleziona un nome</h5><br>
          <div class="input-field">
          <%= form.label :name %><br />
          <%= form.text_field :name, autocomplete: "off" %>
        </div>
        </div>
        <div class="section col s12 m6">
          <h5>Seleziona data e ora</h5><br>
            <div class="input-field row center-align">
              <div class="col s6">
                <a style="margin: 0.2em" class= "btn waves-effect waves-light green darken-2" id="date_input">Data
                  <i class="material-icons right">date_range</i>
                </a>
              </div>
              <div class="col s6">
                <a style="margin: 0.2em" class=" btn waves-effect waves-light green darken-2" id="time_input">Orario
                  <i class="material-icons right">access_time</i>
                </a>
              </div>
            </div>
        </div>
      </div>

    <h5>Seleziona un luogo</h5>
    <div class="input-field">
        <input id="pac-input" class="controls" type="text" placeholder="Indirizzo" >
        <div id="map" style="height:300px;margin-top:2em"></div>
    </div>
    <div class="row">
      <h5>Aggiungi altri giocatori</h5>
      <div class="col s12">
        <div class="row">
          <div class="chips">
            <% if @free_march_users.present? %>
            <% @free_march_users.each do |user| %>
            <div class="chip">
              <% if user && user.avatar.present?%>
              <%= image_tag user.avatar, :class =>"circle avatar", :alt=>"Contact Person"%>
              <% else %>
              <% if user && user.remote_avatar_url != nil%>
              <%= image_tag user.remote_avatar_url, :class =>"circle avatar", :alt=>"Contact Person"%>
              <% end %>
              <% end %>
              <%= user.email%>
            </div>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <div class="actions">
    <!--%= form.submit %-->
    <%= button_tag(type: 'submit', class: "green darken-3 btn waves-effect waves-light right",name: 'action', disabled: true) do %>
      <i class="fas fa-futbol" ></i> Salva
    <% end %>
    <%= link_to free_matches_path, class: "left btn green darken-2 waves-effect waves-light btn-primary" do %>
    Indietro<i class="left material-icons">chevron_left</i>
    <%end%>
    <br>
  </div>
  <script>
        // This example adds a search box to a map, using the Google Place Autocomplete
        // feature. People can enter geographical searches. The search box will return a
        // pick list containing a mix of places and predicted search terms.

        // This example requires the Places library. Include the libraries=places
        // parameter when you first load the API. For example:
        // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

        //document.addEventListener("turbolinks:load", function() {
        formFreeMatch();
      </script>
<% end %>
<script>


  document.addEventListener('turbolinks:before-visit', function() {
    elem2 = document.querySelector('.chips');
    instance2 = M.Chips.getInstance(elem2);
    if (instance2){
      instance2.destroy();
    }
  });

  document.addEventListener('turbolinks:load', function() {
    var elem = document.querySelector('.chips');
    var options = {
      autocompleteOptions:{

      data: {
        <% @users_to_invite.each do |user,index| %>
        <% if user.avatar.present?%>
        '<%= user.email %>':'<%= user.avatar %>',
        <% elsif %>
        <%if user.remote_avatar_url != nil%>
        '<%= user.email %>':'<%=user.remote_avatar_url%>',
        <%end%>
        <%end%>
        <%end%>
        },
        limit: Infinity,
        minLength: 1
      },
        placeholder: 'Cerca un utente',
        secondaryPlaceholder: '+1?',
        onChipDelete: function(elem){
          var index = $(elem[0].M_Chips.$chips).size();
          if(index == 0){
            $('button[name="action"]').disabled = true;
            $('button[name="action"]').prop('disabled', true);
          }
        },
        onChipAdd: function(elem,x){
          var index = $(elem[0].M_Chips.$chips).size();
          $(elem[0].M_Chips.$chips[index - 1]);
          //console.log($(elem[0].M_Chips));
          $('<input>').attr({
            type: 'hidden',
            name: 'player_to_add[]',
            value: elem[0].M_Chips.chipsData[index - 1].tag
          }).appendTo('form#free_match_form');
          if($('input[name="free_match[latitude]"]').val())
            if($('input[name="free_match[date]"]').val()) {
                $('button[name="action"]').disabled = false;
                $('button[name="action"]').prop('disabled', false);
                }
              }
    };
    $('input[name="team[name]"]').attr("autocomplete","off");
    var instances = M.Chips.init(elem, options);
    var instance = M.Chips.getInstance(elem);
    //console.log(instance);
  });
</script>
<style>
  .chips .input{
    width: 100% !important;
  }
  .chips input::placeholder{
    color:black;
    opacity: 0.5; /* Firefox */
    font-weight: 400;
  }
  .chips{
    border:none;
  }
  .chip{
  }
</style>

app/views/free_matches/edit.html.erb
<div class="container">
  <div class=" card section">
      <%= render 'edit_form', free_match: @free_match %>
  </div>
</div>

app/views/free_matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Free Matches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @free_matches.each do |free_match| %>
      <tr>
        <td><%= link_to 'Show', free_match %></td>
        <td><%= link_to 'Edit', edit_free_match_path(free_match) %></td>
        <td><%= link_to 'Destroy', free_match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Free Match', new_free_match_path %>

app/views/free_matches/new.html.erb
<div class="container">
  <div class=" card section">
    <div class="card-header" style="margin-top:1em">
        <div class="col s12">
          <a  class="breadcrumb grey-text text-lighten-1">Nuova Amichevole</a>
          <a  class="breadcrumb green-text text-darken-3">Organizzazione</a>
        </div>
    </div>
    <div class="card-content"><br>
      <%= render 'form', free_match: @free_match %>
    </div>
  </div>
</div>

app/views/free_matches/show.html.erb
<div class="row">
  <div class="container">
    <br>
    <div class="card">
      <div class="card-header row valign-wrapper" style="margin:0;padding:0;height:100%">
        <div class="col s1 row" style="margin:0;padding:0">
          <div class="col s12" style="padding:0;margin:1em">
            <h6 class="center-align green-text text-darken-3"style="margin:0"><%=@free_match.date.strftime("%b").upcase%></h6>
            <h5 class="center-align black-text"style="margin:0"><%=@free_match.date.strftime("%d")%></h5>
          </div>
        </div>
        <div class="col s11 ">
          <div class="left-align">
            <h5>
              <%= @free_match.name %>
            </h5>
          </div>
        </div>
      </div>
      <div class="divider"></div>
      <div class="section" style="padding:0 1em 0 1em">
        <p><i class="material-icons left">access_time</i><%=@free_match.date.strftime("%A %d/%B/%y - %H:%M")%></p>
        <p><i class="material-icons left">place</i><p class="address">Luogo con utilizzo Google Places API</p></p>
      </div>
      <!--div class="row">
        <div class="section">
        DESCRIZIONE IN FUTURO??
        </div>
      </div-->
      <div class="card-image">
        <div id="map" style="height:200px"></div>
      </div>
      <ul class="card-content collection" style="margin:0;padding:0">
        <% @free_match.users.each do |user| %>
        <li class="collection-item avatar">
          <%if user.has_role?(:manager, @free_match) %>
          <span class="new badge " data-badge-caption="manager"></span>
          <% elsif user.has_role?(:member, @free_match) %>
          <span class="new badge" data-badge-caption="membro"></span>
          <% end %>
          <% if user.avatar.present?%>
          <%= image_tag user.avatar, :class =>"circle avatar" %>
          <% else %>
          <% if user.remote_avatar_url != nil%>
          <%= image_tag user.remote_avatar_url, :class =>"circle avatar " %>
          <% end %>
          <% end %>
          <span class="title"><%= link_to user.name, user_path(user)%></span>
          <p><%= user.email %><br>
          Ruolo preferito:
          <%if user.soccer_role == 0%>
          Universale
          <%elsif user.soccer_role == 1%>
          Portiere
          <%elsif user.soccer_role == 2%>
          Difensore
          <%elsif user.soccer_role == 3%>
          Ala
          <%elsif user.soccer_role == 4%>
          Pivot
          <%else%>
          Nessun Ruolo
          <%end%>
          </p>
        </li>
        <% end %>
      </ul>
      <% if Notification.where(notifiable: @free_match, action:"requested").empty? == false %>
      <ul class="card-content collection with-header" style="margin:0;padding:0">
        <% Notification.where(notifiable: @free_match, action:"requested").each do |notification| %>
        <% user = notification.actor %>
        <li class="collection-header"><h6>Richieste</h6></li>
        <li class="collection-item avatar">
          <% if user.avatar.present?%>
          <%= image_tag user.avatar, :class =>"circle avatar" %>
          <% else %>
          <% if user.remote_avatar_url != nil%>
          <%= image_tag user.remote_avatar_url, :class =>"circle avatar " %>
          <% end %>
          <% end %>
          <span class="title"><%= link_to user.name, user_path(user)%></span>
          <p><%= user.email %><br>
          Ruolo preferito:
          <%if user.soccer_role == 0%>
          Universale
          <%elsif user.soccer_role == 1%>
          Portiere
          <%elsif user.soccer_role == 2%>
          Difensore
          <%elsif user.soccer_role == 3%>
          Ala
          <%elsif user.soccer_role == 4%>
          Pivot
          <%else%>
          Nessun Ruolo
          <%end%>
          </p>
          <%= link_to accept_free_match_request_path(@free_match,user), :class => "secondary-content",method: "post" do%>
          <i class="material-icons">add</i>
          <%end%>
        </li>
        <%end%>
      </ul>
      <%end%>
      <% if (Notification.where(recipient: current_user, notifiable: @free_match, action: "invited").present? && !@free_match.users.where(id: current_user.id).present? || current_user && current_user.has_role?(:manager, @free_match)) && !@free_match.date.past?%>
      <div class="card-action">
        <% if Notification.where(recipient: current_user, notifiable: @free_match, action: "invited").present? && !@free_match.users.where(id: current_user.id).present?%>
        <%= form_tag(add_free_match_player_path(@free_match), :method => 'post') do %>
          <%= submit_tag "Accetta invito", class: "btn-flat green draken-2 white-text" do %>
          <i class="material-icons left">add</i>
          <%end%>
        <% end%>
        <%end%>
        <% if current_user && current_user.has_role?(:manager, @free_match)%>
          <% if !@free_match.date.past? %>
          <%= link_to 'Modifica', edit_free_match_path(@free_match) , class: ''%>
          <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>

  var marker;
  var map;
  function initMap() {
    var point = {lat: <%= @free_match.latitude%>, lng:<%= @free_match.longitude%>, zoom: 17};
    var latlng = new google.maps.LatLng(point.lat, point.lng);
    map = new google.maps.Map($('#map')[0], {
        zoom: point.zoom,
        center: latlng,
        styles: [
            {
                "featureType": "landscape",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#FFA800"
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "landscape.man_made",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "landscape.man_made",
                "elementType": "geometry",
                "stylers": [
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "poi",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#679714"
                    },
                    {
                        "saturation": 33.4
                    },
                    {
                        "lightness": -25.4
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "poi.attraction",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.business",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.government",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.medical",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.park",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "poi.place_of_worship",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.school",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.sports_complex",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "road",
                "elementType": "labels.text",
                "stylers": [
                    {
                        "lightness": "65"
                    }
                ]
            },
            {
                "featureType": "road.highway",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#53FF00"
                    },
                    {
                        "saturation": -73
                    },
                    {
                        "lightness": 40
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "road.arterial",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#FBFF00"
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "road.local",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#00FFFD"
                    },
                    {
                        "lightness": 30
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "transit.station",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "water",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#00BFFF"
                    },
                    {
                        "saturation": 6
                    },
                    {
                        "lightness": 8
                    },
                    {
                        "gamma": 1
                    }
                ]
            }
        ]
    });
    geocoder = new google.maps.Geocoder();
    geocoder.geocode({
          'latLng': latlng
      }, function (results, status) {
          if (status ==
              google.maps.GeocoderStatus.OK) {
              if (results[1]) {
                  $('p.address').html(''+results[1].formatted_address);
              } else {
                  console.log('No results found');
              }
          } else {
                console.log('Geocoder failed due to: ' + status);
          }
      });
    marker= new google.maps.Marker({
        position: latlng,
        map: map
    });
  };

  if(window.google){
    initMap();
  } else{
    $.ajax('https://maps.googleapis.com/maps/api/js?key=AIzaSyCWh_byq1Enlj6gXyUks9uPvAMzscT4vTU&callback=initMap', {
      crossDomain: true,
      dataType: 'script'
    });
  }
</script>