config/routes.rb
Rails.application.routes.draw do

  #errrs routes
  match "/404", :to => "errors#error_404", :via => :all
  match "/500", :to => "errors#error_500", :via => :all
  match "/422", :to => "errors#error_422", :via => :all

  #routes for Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  authenticated :user do
      #routes for root AUTHENTICATED
      get '/', :to => 'home#index', as:'home'
  end


  #routes for root NOT AUTHENTICATED
  root 'home#splash'

  #routes that require authentication
  authenticated do

    #routes for resources
    resources :matches #, except: [:index]
    resources :free_matches #, except: [:index]
    resources :teams #, except: [:index]
    resources :users, only: [:show]
    resources :notifications do
      collection do
        post :mark_as_read
      end
    end


    # routes for my autocomplete via Ajax
    get '/autocomplete/:q', :to => 'searches#autocomplete_users',as:'autocomplete_users'

    # routes for the searches
    get '/search', :to =>'searches#search',as: 'search'

    #routes for model User
    match 'users/:id' => 'users#show', via: :get
    match 'users/:id/settings' => 'users#settings', via: :get, as: 'user_settings'
    get 'users/:id' => 'users#show'
    get 'users/:id/set_soccer_role', :to =>'users#set_soccer_role', as: 'set_soccer_role'
    post 'users/:id/set_soccer_role', :to =>'users#update_soccer_role', as: 'update_soccer_role'
    get 'users/:id/matches_info', :to =>'users#matches_info', as: 'matches_info'

    #routes for model Team
    get 'teams/:id/edit_members_roles', :to => 'teams#edit_members_roles', as: 'edit_members_roles'
    post 'teams/:id/update_members_roles', :to => 'teams#update_members_roles', as: 'update_members_roles'
    get 'teams/:id/select_new_players', :to => 'teams#select_new_players', as: 'select_new_players'
    post 'teams/:id/invite', :to => 'teams#invite', as: 'invite'
    post 'teams/:id/add_player', :to => 'teams#add_player', as: 'add_team_player'

    #routes for model Match
    get '/new_match_set_type', :to => 'matches#new_set_type', as:'new_match_set_type'
    post 'matches/:id/set_match_scores', :to =>'matches#set_match_scores', as: 'set_match_scores'
    post 'matches/:id/accept_team_request', :to => 'matches#accept_request', as: 'accept_match_request'
    get 'matches/:id/set_score', :to => 'matches#set_score', as: 'set_match_score'
    post 'matches/:id/update_score', :to => 'matches#update_score', as: 'update_match_score'

    #routes for model FreeMatch
    post 'free_match/:id/add_player', :to => 'free_matches#add_player', as: 'add_free_match_player'
    post 'free_matches/:id/request', :to => 'free_matches#request_free_match', as: 'request_free_match'
    post 'free_matches/:id/accept_request/:uid', :to => 'free_matches#accept_request', as: 'accept_free_match_request'

    #routes to Follow/Unfollow via Ajax
    get '/follow/:following_id/:follower_id', :to => 'users#follow', as: 'follow'
    get '/unfollow/:following_id/:follower_id', :to => 'users#unfollow', as: 'unfollow'

  end
end

app/models/match.rb
class Match < ApplicationRecord
  resourcify
  NUMBER_OF_PERMITTED_TEAMS = 2
  has_and_belongs_to_many :teams, before_add: :validate_team_limit

  validates :date, presence:{message: "mancante"}
  validates :latitude, presence:{message: "mancante"}
  validates :longitude, presence:{message: "mancante"}

  private

  def validate_team_limit(team)
    raise Exception.new if teams.size >= NUMBER_OF_PERMITTED_TEAMS
  end

  after_destroy :delete_dependent_story?

  private

  def delete_match_users
    teams.each do |team|
      team.remove_role :manager, self
      team.destroy
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy,:set_match_scores]
  before_action :authenticate_user!

  # GET /matches/1/set_score
  def set_score
    @match = Match.find(params[:id])
    if Match.find(params[:id]).date.past? == false
      redirect_to match_path(Match.find(params[:id])), notice: 'Il match non è ancora finito!'
    end
    @match.teams.each do |team|
      if(team.has_role?(:manager, @match))
        @home_team = team
      else
        @host_team = team
      end
    end
  end

  #GET
          def accept_request
    @match = Match.find(params[:id])
    @home_team = Team.with_role(:manager,@match)
    @host_team = TeamNotification.where(actor: @home_team, action: "invited",notifiable: @match).first.recipient
    @match.teams << @host_team
    @host_team.add_role(:member,@match)
    TeamNotification.where(actor: @home_team, action: "invited",notifiable: @match).first.delete
    redirect_to @match, notice: "La tua squadra ha confermato l'invito"
  end

  #POST
  def set_match_scores
    if Match.find(params[:id]).date.past? == false
      redirect_to match_path(Match.find(params[:id])), notice: 'Il match non è ancora finito!'
    end
    if @match.home_score != nil
      redirect_to match_path(Match.find(params[:id])), notice: 'Hai già settato il punteggio di questa partita'
    end
    @match.home_score = params[:home_score]
    @match.host_score = params[:host_score]
    if(params[:host_score].to_i > params[:home_score].to_i)
      @host_team = Team.with_role(:team,@match)
      @match.winner_team_id = @host_team.first.id
      @match.save
    else
      @home_team = Team.with_role(:manager,@match)
      @match.winner_team_id = @home_team.first.id
      @match.save
    end
    redirect_to @match, notice: 'Punteggio salvato correttamente.'
  end

  # POST
  def update_score
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /matches
  # GET /matches.json
  def index
  #  @matches = Match.all
  redirect_to root_path
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    if(@match.teams.count >0)
      @match.teams.each do |team|
        team.users.each do |user|
          if(user.id == current_user.id)
            @user_team = Team.find(team.id)
          end
        end
      end
      @match.teams.each do |team|
        if(team.has_role?(:manager, @match))
          @home_team = team
        else
          @host_team = team
        end
      end
    end
    if(@match.teams.count ==1)
      @home_team = Team.with_role(:manager, @match).first
      @host_team = TeamNotification.where(actor: @home_team, action: "invited",notifiable: @match).first.recipient
    end
  end

  # GET /matches/new
  def new
    if current_user.teams.count != 0
      if params[:type].present? == false
        redirect_to new_match_set_type_path
      else
      @type = params[:type]
      @match = Match.new
      end
    else
      redirect_to root_path, notice: 'Non hai ancora una squadra!' 
    end
  end

  # GET /matches/1/edit
  def edit
    if Match.find(params[:id]).date.past? == true && @match.home_score != nil
      redirect_to match_path(Match.find(params[:id])), notice: 'Non puoi modificare ua partita finita'
    end
    if(@match.teams.count >1)
      @match.teams.each do |team|
        team.users.each do |user|
          if(user.id == current_user.id)
            @user_team = Team.find(team.id)
          end
        end
      end
      @match.teams.each do |team|
        if(team.has_role?(:manager, @match))
          @home_team = team
        else
          @host_team = team
        end
      end
    end
    if(@match.teams.count ==1)
      @home_team = Team.with_role(:manager, @match).first
      @host_team = TeamNotification.where(actor: @home_team, action: "invited",notifiable: @match).first.recipient
    end
  end

  def new_set_type
  end

  # POST /matches
  # POST /matches.json
  def create

    @match = Match.new(match_params)

    # Quando creo un primo match senza assegnarlo ad una squadrea in casa e ospite assegno un ruolo temporaneo all'utente che lo crea

    respond_to do |format|
      p params[:match][:date]
      #@date_parsed = DateTime.strptime(params[:match][:date], "%Y-%m-%d %H:%M:S")
      @match.date = DateTime.parse(params[:match][:date])
      if @match.save
        match = @match
        Activity.create(actor: current_user, action: "created",object: match)
        @home_team = Team.where(name: params[:home]).first
        @home_team.add_role(:manager, @match)
        @match.teams << @home_team
        @host_team = Team.where(name: params[:host]).first
        #@host_team.add_role(:team,@match)
        #@match.teams << @host_team
        TeamNotification.create(recipient: @host_team, actor: @home_team, action: "invited",notifiable: @match)
        current_user.add_role(:manager, @match)
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    old_home_team = Team.with_role(:manager,@match).first
    new_home_team = Team.where(name: params[:home]).first
    if @match.teams.count == 1
      old_host_team = TeamNotification.where(actor: @home_team, action: "invited",notifiable: @match).first.recipient
      new_host_team = Team.where(name: params[:host]).first
      if old_host_team != new_host_team
        TeamNotification.where(actor: old_home_team, action: "invited",notifiable: @match).delete
        TeamNotification.create(recipient: new_host_team, actor: new_home_team, action: "invited",notifiable: @match)
      end
      if old_home_team != new_home_team
        old_home_team.remove_role(:manager, @match)
        @match.teams.delete_all
        @match.teams << new_home_team
        new_home_team.add_role(:manager,@match)
      end
    elsif @match.teams.count == 2
      new_host_team = Team.where(name: params[:host]).first
      old_host_team = Team.with_role(:team,@match)
      old_home_team.remove_role(:manager,@match)
      old_host_team.remove_role(:manager,@match)
      new_home_team.add_role(:manager,@match)
      @match.teams.delete_all
      @match.teams << new_home_team
      TeamNotification.create(recipient: new_host_team, actor: new_home_team, action: "invited",notifiable: @match)
    end
    @match.date = DateTime.parse(params[:match][:date])
    respond_to do |format|
      if @match.update(match_params)
        @home_team = Team.with_role(:manager,@match)
        @host_team = TeamNotification.where(actor: new_home_team, action: "invited",notifiable: @match).first.recipient
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    TeamNotification.where(notifiable:@match).each do |notification|
      notification.delete
    end
    Activity.where(object:@match).each do |activity|
      activity.delete
    end
    @match.teams.each do |team|
      if team.has_role?(:manager, @match)
        team.remove_role(:manager,@match)
      end
      if team.has_role?(:member, @match)
        team.remove_role(:member,@match)
      end
    end
    @match.delete
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:date, :latitude, :longitude, :host, :home, :host_score, :home_score,:tipologia,:type)
      #params.fetch(:match, {})
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_edit_form.html.erb
<div class="card-content">
  <%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :tipologia, :value => match.tipologia %>
  <%= form.hidden_field :date, :value => match.date%>
  <%= form.hidden_field :latitude, :value => match.latitude%>
  <%= form.hidden_field :longitude, :value => match.longitude %>
  <div class="container center-align">
    <h5>Seleziona Data e Ora</h5>
    <a class="btn waves-effect waves-light green darken-2" id="date_input">
      <%=match.date.strftime("%d/%m/%Y")%>
    </a>
    <a class="btn waves-effect waves-light green darken-2" id="time_input">
      <%=match.date.strftime("%H:%M")%>
    </a>

    <div class="input-field center-align">
        <input id="pac-input" class="controls" type="text" placeholder="Indirizzo" >
        <div id="match_map" style="height:300px;margin-top:2em"></div>
    </div>
    <h5>Seleziona le squadre</h5>
    <div class="row">
    <div class="col s5 input-field">
      <i class="icon-soccer-shoe prefix"></i>
        <input type="text" name="home" id="home-input" class="autocompletehome" value="<%=@home_team.name%>" style="text-align:center" autocomplete="off">
        <label for="home-input" class="active"style="text-align:center">Casa</label>
    </div>
    <div class="col s2"><h6>VS</h6></div>
    <div class="col s5 input-field">
        <i class="icon-soccer-shoe prefix"></i>
        <input type="text" name="host" id="host-input" class="autocompletehost" value="<%=@host_team.name%>" style="text-align:center" autocomplete="off">
        <label for="host-input" class="active" style="text-align:center">Ospite</label>
    </div>
    <div class="actions">
      <!--%= form.submit %-->


    </div>
  </div>
  </div>
  <div class="row center-align">
    <div class="col s4">
      <%= link_to root_path, class: " darken-2 btn green darken-3 waves-effect waves-light" do %>
      <%=t(:back)%><i class="material-icons left">chevron_left</i>
      <%end%>
    </div>
    <div class="col s4">
      <%= button_tag(type: 'submit', class: "green darken-3 btn waves-effect waves-light",name: 'action', disabled: false) do %>
        <i class="icon-soccer-court left "></i> Salva
      <% end %>
    </div>
    <% end %>
    <%= form_tag(match_path(@match),class:"col s4 ", :method => 'delete') do %>
    <%= button_tag(type: "submit",class: "btn red",data: { confirm: "sei sicuro di volerlo cancellare?" } ) do %>
        Cancella<i class="material-icons left">delete</i>
    <% end %>
    <% end%>
  </div>
  <script>
    document.addEventListener('turbolinks:load', function() {
    var home = {
      /*
        <%= current_user.teams.count %>
      */
      <% current_user.teams.each do |team| %>
      <% if current_user.has_role?(:manager, team) %>
      <% if team.calcetto && match.tipologia == "calcetto" %>
      '<%= team.name %>':null,
      <%elsif team.calciotto && match.tipologia == "calciotto" %>
      '<%= team.name %>':null,
      <% end %>
      <%end%>
      <%end%>
    };
    var host =  {
      <% (Team.all - current_user.teams).each do |team| %>
      <% if team.calcetto && match.tipologia == "calcetto" %>
      '<%= team.name %>':null,
      <%elsif team.calciotto && match.tipologia == "calciotto" %>
      '<%= team.name %>':null,
      <% end %>
      <%end%>
    };
    formMatchEdit(home,host);
  });
  </script>

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :tipologia, :value => @type %>
  <%= form.hidden_field :date %>
  <%= form.hidden_field :latitude %>
  <%= form.hidden_field :longitude %>

    <div class="row">
      <h5>Seleziona Data e Ora</h5>
      <div class="section col s12">
          <div class="input-field">
        <a style="width: 50%;margin: 0.2em" class= "btn waves-effect waves-light green darken-2" id="date_input">Data
          <i class="material-icons right">date_range</i>
        </a>
        <a style="width: 50%;margin: 0.2em" class=" btn waves-effect waves-light green darken-2" id="time_input">Orario
          <i class="material-icons right">access_time</i>
        </a>
      </div>
      </div>
    </div>

    <div class="input-field center-align">
        <input id="pac-input" class="controls" type="text" placeholder="Indirizzo" >
        <div id="map" style="height:300px;margin-top:2em"></div>
    </div>
    <h5>Seleziona le squadre</h5>
    <div class="row">
    <div class="col s5 input-field">
      <i class="icon-soccer-shoe prefix"></i>
        <input type="text" name="home" id="home-input" class="autocompletehome" style="text-align:center" autocomplete="off">
        <label for="home-input" style="text-align:center">Casa</label>
    </div>
    <div class="col s2 center-align"><h6>VS</h6></div>
    <div class="col s5 input-field">
        <i class="icon-soccer-shoe prefix"></i>
        <input type="text" name="host" id="host-input" class="autocompletehost" style="text-align:center" autocomplete="off">
        <label for="host-input" style="text-align:center">Ospite</label>
    </div>
  </div>
  <div class="actions">
    <!--%= form.submit %-->
    <%= link_to root_path, class: "darken-2 green darken-3 btn waves-effect left waves-light" do %>
    <%=t(:cancel)%><i class="material-icons left">cancel</i>
    <%end%>
    <%= button_tag(type: 'submit', class: "green darken-3 btn right waves-effect waves-light",name: 'action', disabled: true) do %>
      <i class="icon-soccer-court left "></i> Procedi
    <% end %>
  </div>
  <br>
  <script>
    document.addEventListener('turbolinks:load', function() {
    var home = {
      /*
        <%= current_user.teams.count %>
      */
      <% current_user.teams.each do |team| %>
      <% if current_user.has_role?(:manager, team) %>
      <% if team.calcetto && @type == "calcetto" %>
      '<%= team.name %>':null,
      <%elsif team.calciotto && @type == "calciotto" %>
      '<%= team.name %>':null,
      <% end %>
      <%end%>
      <%end%>
    };
    var host =  {
      <% (Team.all - current_user.teams).each do |team| %>
      <% if team.calcetto && @type == "calcetto" %>
      '<%= team.name %>':null,
      <%elsif team.calciotto && @type == "calciotto" %>
      '<%= team.name %>':null,
      <% end %>
      <%end%>
    };
    formMatch(home,host);
    });
  </script>
<% end %>

app/views/matches/edit.html.erb
<div class="container">
  <div class="section card">
    <%= render 'edit_form', match: @match %>
  </div>
</div>

app/views/matches/index.html.erb
<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<div class="container">
  <div class="section card">
    <div class="card-header" style="margin-top:1em">
        <div class="col s12">
          <a  class="breadcrumb grey-text text-lighten-1">Tipologia</a>
          <a  class="breadcrumb green-text text-darken-3">Organizzazione</a>
        </div>
    </div>
    <div class="card-content"><br>
      <%= render 'form', match: @match %>
    </div>
  </div>
</div>


<!--%= link_to matches_path do %>
<%= t(:back) %><i class="material-icons left">chevron_left</i>
<%end%-->

app/views/matches/set_score.html.erb
<%= render 'set_score_form', match: @match %>

app/views/matches/show.html.erb
<div class="row">
  <div class="container">
    <br>
    <div class="card">
      <div class="card-header" style="margin:0;padding:0;height:100%">
        <!--div class="col s1 row" style="margin:0;padding:0">
          <div class="col s12" style="padding:0;margin:1em">
            <h6 class="center-align green-text text-darken-3"style="margin:0"><%=@match.date.strftime("%b").upcase%></h6>
            <h5 class="center-align black-text"style="margin:0"><%=@match.date.strftime("%d")%></h5>
          </div>
        </div-->
        <div class="row valign-wrapper" style="margin:0;padding:1em">
          <div class="col s4" >
            <a class="center-align" href="<%=team_path(@home_team)%>">
              <div class="row" style="margin:0">
                <div class="col s12">
                  <%= image_tag @home_team.avatar, :class =>"circle avatar responsive-img", :style =>"width:42px;height:42px"%>
                </div>
                <div class="col s12">
                  <span  class="truncate"><%=@home_team.name%></span>
                </div>
              </div>
            </a>
          </div>
          <div class="col s4 center-align " >
            <% if @match.home_score == nil %>
            <span>VS</span>

            <% else %>
            <h3><%=@match.home_score%> - <%=@match.host_score%></h3>
            <% end %>
          </div>
          <div class="col s4 " >
            <% if TeamNotification.where(actor: @home_team, action: "invited",notifiable: @match).empty? == false && @match.teams.count == 1 %>
            <a class="center-align">
              <div class="row" style="margin:0">
                <div class="col s12">
                  <%= image_tag @host_team.avatar, :class =>"circle avatar responsive-img", :style =>"width:42px;height:42px"%>
                </div>
                <div class="col s12">
                  <span  class="truncate"><%=@host_team.name%>???</span>
                </div>
              </div>
            </a>
            <%else%>
            <a class="center-align" href="<%=team_path(@host_team)%>">
              <div class="row" style="margin:0">
                <div class="col s12">
                  <%= image_tag @host_team.avatar, :class =>"circle avatar responsive-img", :style =>"width:42px;height:42px"%>
                </div>
                <div class="col s12">
                  <span  class="truncate"><%=@host_team.name%></span>
                </div>
              </div>
            </a>
            <%end%>
          </div>
        </div>
      </div>
      <div class="divider"></div>
      <div class="section" style="padding:0 1em 0 1em">
        <p><i class="material-icons left">access_time</i><%=@match.date.strftime("%A %d/%B/%y - %H:%M")%></p>
        <p><i class="material-icons left">place</i><p class="address">Luogo con utilizzo Google Places API</p></p>
      </div>
      <div class="divider"></div>
      <div class="section" style="padding:0 1em 0 1em">
      </div>
      <!--div class="row">
        <div class="section">
        DESCRIZIONE IN FUTURO??
        </div>
      </div-->
      <div class="card-image">
        <div id="map" style="height:200px"></div>
      </div>
      <% if current_user && (current_user.has_role?(:manager, @home_team) || current_user.has_role?(:manager, @host_team)) && @match.home_score == nil %>
      <div class="card-action">
        <% if current_user.has_role?(:manager,@home_team) && @match.date.past? && @match.home_score == nil%>
        <% if @match.teams.count == 2 %>
        <%= link_to 'Segna Punteggio', set_match_score_path(@match) %>
        <% else %>
        <p class="btn-flat grey darken-2 white-text" style="color:white !important"><i class="material-icons left">hourglass_empty</i>In attesa di conferma"</p>
        <% end %>
        <% end %>
        <% if current_user.has_role?(:manager, @host_team) && @host_team.has_role?(:member,@match) == false %>
        <%= button_to accept_match_request_path(@match), method: :post, class: 'btn-flat btn-danger' do %>
        Accetta Invito
        <% end %>
        <%end%>
        <% if !@match.date.past? %>
        <%= link_to 'Modifica', edit_match_path(@match) , class: ''%>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  var marker;
  var map;
  function initMap() {
    var point = {lat: <%= @match.latitude%>, lng:<%= @match.longitude%>, zoom: 17};
    var geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(point.lat, point.lng);   // turn coordinates into an object
    geocoder.geocode({'latLng': latlng}, function (results, status){
      if(status == google.maps.GeocoderStatus.OK) {           // if geocode success
      console.log(results[0].formatted_address);
      $('p.address').html(results[0].formatted_address);
      }
    });
    map = new google.maps.Map($('#map')[0], {
        zoom: point.zoom,
        center: latlng,
        styles: [
            {
                "featureType": "landscape",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#FFA800"
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "landscape.man_made",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "landscape.man_made",
                "elementType": "geometry",
                "stylers": [
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "poi",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#679714"
                    },
                    {
                        "saturation": 33.4
                    },
                    {
                        "lightness": -25.4
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "poi.attraction",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.business",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.government",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.medical",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.park",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "poi.place_of_worship",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.school",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.sports_complex",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "road",
                "elementType": "labels.text",
                "stylers": [
                    {
                        "lightness": "65"
                    }
                ]
            },
            {
                "featureType": "road.highway",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#53FF00"
                    },
                    {
                        "saturation": -73
                    },
                    {
                        "lightness": 40
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "road.arterial",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#FBFF00"
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "road.local",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#00FFFD"
                    },
                    {
                        "lightness": 30
                    },
                    {
                        "gamma": 1
                    }
                ]
            },
            {
                "featureType": "transit.station",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "water",
                "elementType": "all",
                "stylers": [
                    {
                        "hue": "#00BFFF"
                    },
                    {
                        "saturation": 6
                    },
                    {
                        "lightness": 8
                    },
                    {
                        "gamma": 1
                    }
                ]
            }
            ]
            });

    marker= new google.maps.Marker({
        position: latlng,
        map: map
    });
  };

  if(window.google){
    initMap();
  } else{
    $.ajax('https://maps.googleapis.com/maps/api/js?key=AIzaSyCWh_byq1Enlj6gXyUks9uPvAMzscT4vTU&callback=initMap', {
      crossDomain: true,
      dataType: 'script'
    });
  }
</script>