config/routes.rb
Rails.application.routes.draw do

  #errrs routes
  match "/404", :to => "errors#error_404", :via => :all
  match "/500", :to => "errors#error_500", :via => :all
  match "/422", :to => "errors#error_422", :via => :all

  #routes for Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  authenticated :user do
      #routes for root AUTHENTICATED
      get '/', :to => 'home#index', as:'home'
  end


  #routes for root NOT AUTHENTICATED
  root 'home#splash'

  #routes that require authentication
  authenticated do

    #routes for resources
    resources :matches #, except: [:index]
    resources :free_matches #, except: [:index]
    resources :teams #, except: [:index]
    resources :users, only: [:show]
    resources :notifications do
      collection do
        post :mark_as_read
      end
    end


    # routes for my autocomplete via Ajax
    get '/autocomplete/:q', :to => 'searches#autocomplete_users',as:'autocomplete_users'

    # routes for the searches
    get '/search', :to =>'searches#search',as: 'search'

    #routes for model User
    match 'users/:id' => 'users#show', via: :get
    match 'users/:id/settings' => 'users#settings', via: :get, as: 'user_settings'
    get 'users/:id' => 'users#show'
    get 'users/:id/set_soccer_role', :to =>'users#set_soccer_role', as: 'set_soccer_role'
    post 'users/:id/set_soccer_role', :to =>'users#update_soccer_role', as: 'update_soccer_role'
    get 'users/:id/matches_info', :to =>'users#matches_info', as: 'matches_info'

    #routes for model Team
    get 'teams/:id/edit_members_roles', :to => 'teams#edit_members_roles', as: 'edit_members_roles'
    post 'teams/:id/update_members_roles', :to => 'teams#update_members_roles', as: 'update_members_roles'
    get 'teams/:id/select_new_players', :to => 'teams#select_new_players', as: 'select_new_players'
    post 'teams/:id/invite', :to => 'teams#invite', as: 'invite'
    post 'teams/:id/add_player', :to => 'teams#add_player', as: 'add_team_player'

    #routes for model Match
    get '/new_match_set_type', :to => 'matches#new_set_type', as:'new_match_set_type'
    post 'matches/:id/set_match_scores', :to =>'matches#set_match_scores', as: 'set_match_scores'
    post 'matches/:id/accept_team_request', :to => 'matches#accept_request', as: 'accept_match_request'
    get 'matches/:id/set_score', :to => 'matches#set_score', as: 'set_match_score'
    post 'matches/:id/update_score', :to => 'matches#update_score', as: 'update_match_score'

    #routes for model FreeMatch
    post 'free_match/:id/add_player', :to => 'free_matches#add_player', as: 'add_free_match_player'
    post 'free_matches/:id/request', :to => 'free_matches#request_free_match', as: 'request_free_match'
    post 'free_matches/:id/accept_request/:uid', :to => 'free_matches#accept_request', as: 'accept_free_match_request'

    #routes to Follow/Unfollow via Ajax
    get '/follow/:following_id/:follower_id', :to => 'users#follow', as: 'follow'
    get '/unfollow/:following_id/:follower_id', :to => 'users#unfollow', as: 'unfollow'

  end
end

app/views/items/_activity_free_match.html.erb
<li style="border-left:none;border-right:none" class="collection-item mi_item free_match_item card" data-la="<%= free_match.latitude%>" data-lo="<%= free_match.longitude %>">
  <div class="collection" style="margin:0;border-left:none;border-right:none">
    <div class="collection-item avatar" >
      <% if action == "created" %>
      <% if actor != ''%>
      <% if actor.avatar.present?%>
      <%= image_tag actor.avatar, :class =>"circle avatar" %>
      <% else %>
      <% if actor.remote_avatar_url != nil%>
      <%= image_tag actor.remote_avatar_url, :class =>"circle avatar " %>
      <% end %>
      <% end %>
      <span class="title"><%= link_to actor.name, user_path(actor), :class =>"green-text text-darken-2" %> ha creato <%= link_to "un'amichevole", free_match_path(free_match), :class =>"green-text text-darken-2"%></span>
      <p><%=l  date, format: "%D"%> alle <%= date.strftime("%H:%M")%></p>
      <% else %>
      <span class="title">Ha creato <%= link_to "un match libero", free_match_path(free_match)%> </span>
      <p><%= l date, format: "%D"%> alle <%= date.strftime("%H:%M")%></p>
      <%end%>
      <%end%>
    </div>
  </div>
  <div class="section" style="padding:0">
    <div class="row valign-wrapper" style="margin:0;padding:0;height:100%">
      <div class="col s3 row" style="margin:0;padding:0">
        <div class="col s12" style="padding:0;margin:1em">
          <h6 class="center-align green-text text-darken-3"style="margin:0"><%=(l free_match.date, format:"%b").upcase%></h6>
          <h5 class="center-align black-text"style="margin:0"><%=l free_match.date, format:"%d"%></h5>
        </div>
      </div>
      <div class="col s9 ">
        <div class="center-align">
          <div>
            <%= free_match.name %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="divider"></div>
  <div class="section" style="padding:0 1em 0 1em">
    <p><i class="material-icons left">access_time</i><%=l free_match.date, format:"%A %d %B %Y - %H:%M"%></p>
    <p><i class="material-icons left">people</i>Partecipanti: <%=free_match.users.count%></p>
    <p><i class="material-icons left">place</i><p class="address">Luogo con utilizzo Google Places API</p></p>
  </div>
  <div class="card-image">
    <div id="map-<%=idmap.to_s%>" style="height:200px"></div>
  </div>
  <!--div class="card-content row">

  </div-->
  <div class="card-action">
    <% if current_user && free_match.users.include?(current_user) == false %>
    <%= link_to "Partecipa", request_free_match_path(free_match), method: :post %>
    <% end %>
  </div>
</li>

app/views/items/_activity_match.html.erb
<li class="collection-item mi_item match_item card" data-la="<%= match.latitude%>" data-lo="<%= match.longitude %>">
  <div class="collection" style="margin:0;border-left:none;border-right:none">
  <div class="collection-item avatar">
      <% if action == "created" %>
      <% if actor != ''%>
      <% if actor.avatar.present?%>
      <%= image_tag actor.avatar, :class =>"circle avatar" %>
      <% else %>
      <% if actor.remote_avatar_url != nil%>
      <%= image_tag actor.remote_avatar_url, :class =>"circle avatar " %>
      <% end %>
      <% end %>
      <span class="title"><%= link_to actor.name, user_path(actor), :class =>"green-text text-darken-2" %> ha creato <%= link_to "una partita", match_path(match), :class =>"green-text text-darken-2"%></span>
      <p><%= date.strftime("%D")%> alle <%= date.strftime("%H:%M")%></p>
      <% else %>
      <span class="title">Ha creato <%= link_to "un match", match_path(match)%> </span>
      <p><%= date.strftime("%D")%> alle <%= date.strftime("%H:%M")%></p>
      <%end%>
      <%end%>
  </div></div>
  <div class="section" style="padding:0">
    <div class="row valign-wrapper" style="margin:0.5em;padding:0;height:100%">
      <div class="col s2 row" style="margin:0;padding:0">
        <h6 class="center-align green-text text-darken-3"style="margin:0"><%=l match.date, format:"%b".upcase%></h6>
        <h5 class="center-align black-text"style="margin:0"><%=match.date.strftime("%d")%></h5>
      </div>
      <div class="col s10 " style="padding:0">
        <div class="center-align">
          <div class="row valign-wrapper" style="margin:0">

            <% home_team = Team.with_role(:manager,match).first %>
            <% if TeamNotification.where(actor: home_team, action: "invited",notifiable: match).empty? == false && match.teams.count == 1 %>
            <% host_team = TeamNotification.where(actor: Team.with_role(:manager,match).first, action: "invited",notifiable: match).first.recipient %>
            <% end %>
            <%if match.teams.count == 2%>
            <% host_team = Team.with_role(:member,match).first %>
            <%end%>
            <div class="col s4 center-align">
              <a href="<%=team_path(home_team)%>">
                <div class="row" style="margin:0">
                  <div class="col s12">
                    <%= image_tag home_team.avatar, :class =>"circle avatar responsive-img"%>
                  </div>
                  <div class="col s12"style="padding:0">
                    <span  class="truncate"><%=home_team.name%></span>
                  </div>
                </div>
              </a>
            </div>
            <div class="col s4 center-align">
              <% if match.home_score == nil %>
              <span>VS</span>
              <% else %>
              <span><%=match.home_score%> - <%=match.host_score%></span>
              <% end %>
            </div>
            <div class="col s4 center-align">
              <a href="<%=team_path(host_team)%>">
                <div class="row" style="margin:0">
                  <div class="col s12">
                    <%= image_tag host_team.avatar, :class =>"circle avatar responsive-img" %>
                  </div>
                  <div class="col s12"style="padding:0">
                    <% if TeamNotification.where(actor: home_team, action: "invited",notifiable: match).empty? == false && match.teams.count == 1 %>
                    <span  class="truncate">???<%=host_team.name%></span>
                    <%else%>
                    <span  class="truncate"><%=host_team.name%></span>
                    <%end%>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="divider"></div>
  <div class="section" style="padding:0 1em 0 1em">
    <p><i class="material-icons left">access_time</i><%=l match.date, format:"%A %d/%B/%y - %H:%M"%></p>
    <p><i class="material-icons left">place</i><p class="address">Luogo con utilizzo Google Places API</p></p>
  </div>
    <div class="card-image">
       <div id="map-<%=idmap.to_s%>" style="height:200px"></div>
        <!--<span class="card-title black-text">Nome della partita</span>-->
       <!--a class="btn-floating halfway-fab waves-effect waves-green white">
         <i class="fas fa-futbol" style="color: black !important"></i></a-->
     </div>

      <% if current_user && current_user.has_role?(:manager, match) && match.home_score == nil%>
      <div class="card-action">
      <a class="valign-wrapper" href="<%= edit_match_path(match) %>"><i class="tiny material-icons left">edit</i>Modifica</a>
    </div>
      <%end%>
</li>

app/views/items/_activity_team.html.erb
<li class="collection-item avatar card " style="margin-top: 1em !important;margin-bottom: 1em !important;">
    <% if action == "created" %>
    <% if actor != ''%>
    <% if actor.avatar.present?%>
    <%= image_tag actor.avatar, :class =>"circle avatar" %>
    <% else %>
    <% if actor.remote_avatar_url != nil%>
    <%= image_tag actor.remote_avatar_url, :class =>"circle avatar " %>
    <% end %>
    <% end %>
    <span class="title"><%= link_to actor.name, user_path(actor), :class =>"green-text text-darken-2" %> ha creato <%= link_to team.name, team_path(team), :class =>"green-text text-darken-2"%></span>
    <p><%= date.strftime("%D")%> alle <%= date.strftime("%H:%M")%></p>
    <% else %>
    <span class="title">Ha creato <%= link_to team.name, team_path(team)%> </span>
    <p><%= date.strftime("%D")%> alle <%= date.strftime("%H:%M")%></p>
    <%end%>
    <%end%>
</li>

app/views/items/_free_match.html.erb
<li class="collection-item mi_item free_match_item card" data-la="<%= free_match.latitude%>" data-lo="<%= free_match.longitude %>">
   <div class="card-image">
     <div id="map-<%=idmap.to_s%>" style="height:200px"></div>
      <span class="card-title black-text"><%= free_match.name%></span>
     <!--a class="btn-floating halfway-fab waves-effect waves-green white">
       <i class="fas fa-futbol" style="color: black !important"></i></a-->
   </div>
    <div class="card-content row valign-wrapper">
      <div class="col s12 m6">
        <h6 class="center-align">
          <i class="material-icons">date_range</i>
          <%= free_match.date.strftime("%D")%>
        </h6>
        <h6 class="center-align">
          <i class="material-icons">access_time</i>
          <%= free_match.date.strftime("%H")%>
        </h6>
      </div>
      <div class="col s12 m6">
      <h6 class="center-align">Partecipanti</h6>
      <h3 class="center-align"><%= free_match.users.count%></h3></div>
    </div>
    <div class="card-action">
          <a href="<%= free_match_path(free_match) %>">Vai alla partita</a>
        </div>
</li>

app/views/items/_match.html.erb
<li class="collection-item mi_item match_item card" data-la="<%= match.latitude%>" data-lo="<%= match.longitude %>">
     <div class="card-image">
       <div id="map-<%=idmap.to_s%>" style="height:200px"></div>
        <!--<span class="card-title black-text">Nome della partita</span>-->
       <!--a class="btn-floating halfway-fab waves-effect waves-green white">
         <i class="fas fa-futbol" style="color: black !important"></i></a-->
     </div>
    <div class="card-content row">
      <% match.teams.each do |team| %>
      <% if team.has_role?(:manager, match) %>
      <div class="col s4 center-align">
        <h6><%= team.name %></h6>
        <img src="https://pbs.twimg.com/profile_images/1011320337/Muppets-4624932-Funny-Cartoons.jpg" alt="" style="width:3em;height:3em" class="circle responsive-img">
      </div>
      <% end %>
      <% end %>
      <div class="col s4 center-align">
        <% if match.home_score == nil %>
        <h3>VS</h3>
        <% else %>
        <h5><%=match.home_score%> - <%=match.host_score%></h5>
        <% end %>
      </div>
      <% match.teams.each do |team| %>
      <% if team.has_role?(:manager, match) == false %>
      <div class="col s4 center-align">
        <h6><%= team.name %></h6>
        <img src="https://pbs.twimg.com/profile_images/1011320337/Muppets-4624932-Funny-Cartoons.jpg" alt="" style="width:3em;height:3em" class="circle responsive-img">
      </div>
      <% end %>
      <% end %>
    </div>
    <div class="card-action">
      <a href="<%= match_path(match) %>">Val alla partita</a>
    </div>
</li>

app/views/items/_team.html.erb
<li class="collection-item card" >
  <div class="card-content">
    <span class="card-title"><%= link_to team.name, team_path(team)%> </span>
  </p><%= %></p>
  </div>
</li>

app/views/items/_user.html.erb
<li class="collection-item avatar">
  <% if user.avatar.present?%>
  <%= image_tag user.avatar, :class =>"circle avatar" %>
  <% else %>
  <% if user.remote_avatar_url != nil%>
  <%= image_tag user.remote_avatar_url, :class =>"circle avatar " %>
  <% end %>
  <% end %>
  <span class="title">
    <%= link_to user.name, user_path(user), :class =>"green-text text-darken-2" %>
  </span>
  <span class="new badge" data-badge-caption="<%=user.get_soccer_role%>"></span>
  <p>followers: <%=user.followers.count%></p>
  <p>following: <%=user.following.count%></p>
</li>