config/routes.rb
Rails.application.routes.draw do

  #errrs routes
  match "/404", :to => "errors#error_404", :via => :all
  match "/500", :to => "errors#error_500", :via => :all
  match "/422", :to => "errors#error_422", :via => :all

  #routes for Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  authenticated :user do
      #routes for root AUTHENTICATED
      get '/', :to => 'home#index', as:'home'
  end


  #routes for root NOT AUTHENTICATED
  root 'home#splash'

  #routes that require authentication
  authenticated do

    #routes for resources
    resources :matches #, except: [:index]
    resources :free_matches #, except: [:index]
    resources :teams #, except: [:index]
    resources :users, only: [:show]
    resources :notifications do
      collection do
        post :mark_as_read
      end
    end


    # routes for my autocomplete via Ajax
    get '/autocomplete/:q', :to => 'searches#autocomplete_users',as:'autocomplete_users'

    # routes for the searches
    get '/search', :to =>'searches#search',as: 'search'

    #routes for model User
    match 'users/:id' => 'users#show', via: :get
    match 'users/:id/settings' => 'users#settings', via: :get, as: 'user_settings'
    get 'users/:id' => 'users#show'
    get 'users/:id/set_soccer_role', :to =>'users#set_soccer_role', as: 'set_soccer_role'
    post 'users/:id/set_soccer_role', :to =>'users#update_soccer_role', as: 'update_soccer_role'
    get 'users/:id/matches_info', :to =>'users#matches_info', as: 'matches_info'

    #routes for model Team
    get 'teams/:id/edit_members_roles', :to => 'teams#edit_members_roles', as: 'edit_members_roles'
    post 'teams/:id/update_members_roles', :to => 'teams#update_members_roles', as: 'update_members_roles'
    get 'teams/:id/select_new_players', :to => 'teams#select_new_players', as: 'select_new_players'
    post 'teams/:id/invite', :to => 'teams#invite', as: 'invite'
    post 'teams/:id/add_player', :to => 'teams#add_player', as: 'add_team_player'

    #routes for model Match
    get '/new_match_set_type', :to => 'matches#new_set_type', as:'new_match_set_type'
    post 'matches/:id/set_match_scores', :to =>'matches#set_match_scores', as: 'set_match_scores'
    post 'matches/:id/accept_team_request', :to => 'matches#accept_request', as: 'accept_match_request'
    get 'matches/:id/set_score', :to => 'matches#set_score', as: 'set_match_score'
    post 'matches/:id/update_score', :to => 'matches#update_score', as: 'update_match_score'

    #routes for model FreeMatch
    post 'free_match/:id/add_player', :to => 'free_matches#add_player', as: 'add_free_match_player'
    post 'free_matches/:id/request', :to => 'free_matches#request_free_match', as: 'request_free_match'
    post 'free_matches/:id/accept_request/:uid', :to => 'free_matches#accept_request', as: 'accept_free_match_request'

    #routes to Follow/Unfollow via Ajax
    get '/follow/:following_id/:follower_id', :to => 'users#follow', as: 'follow'
    get '/unfollow/:following_id/:follower_id', :to => 'users#unfollow', as: 'unfollow'

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dribbler</title>
    <%= csrf_meta_tags %>
    <!-- Meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Links -->
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Roboto|Roboto+Mono" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/solid.css" integrity="sha384-VxweGom9fDoUf7YfLTHgO0r70LVNHP5+Oi8dcR4hbEjS8UnpRtrwTx7LpHq/MWLI" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">

    <script type="text/javascript" src="https://unpkg.com/default-passive-events"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Google Maps Library -->
    <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCWh_byq1Enlj6gXyUks9uPvAMzscT4vTU&libraries=places" data-turbolinks-eval="false"></script>
    <!-- Google Charts Library -->
    <script async src="https://www.gstatic.com/charts/loader.js"></script>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <main>
    <!-- Navbar -->
    <div class="navbar-fixed">
      <nav>

        <div class="nav-wrapper">
            <!--


        -->

      <div class="row" style="height:100%;margin:0">
        <div class="col s2 m4" style="padding:0">
          <ul class="left">
            <li>
              <a style="margin:0" href="#" data-target="sidenav-trigger" class="white-text sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
            </li>
          </ul>

        </div>
        <div class="col s4 m4">
            <div class="center-align">
              <a href="/" class="white-text hide-on-small-only show-on-medium-and-up" style="font-family: 'Pacifico', cursive;font-size:3em">Dribbler</a>
              <a href="/" class="white-text show-on-small hide-on-med-and-up" style="font-family: 'Pacifico', cursive;font-size:2em">Dribbler</a>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="col s4 show-on-small sm-trigger hide-on-med-and-up" style="height:100%">
            <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
            <form class="valign-wrapper" action="/search" method="get">
            <div class="input-field " style="width:100%" name="search">
              <input placeholder="Cerca" id="search_small" class="search-bar small " type="search" name="q" required  autocomplete="off">
              <label class="label-icon" for="search"><i class="material-icons">search</i>
              </label>
              <i class="material-icons closed clear-search-bar">close</i>
              <input type="submit" style="display: none;">
              </form>
            </div>
          </div>
          <div class="col m3 hide-on-small-only show-on-medium-and-up" style="height:100%">
            <div class="input-field " style="width:100%;padding: 0.5em" name="search">
              <form class="valign-wrapper" action="/search" method="get">
              <input placeholder="Cerca" id="search" class="search-bar " type="search" name="q" required  autocomplete="off">
              <label class="label-icon" for="search" style="position:absolute"><i class="material-icons">search</i>
              </label>
              <i class="material-icons closed clear-search-bar">close</i>
              <input type="submit" style="display: none;">
              </form>
            </div>
          </div>
        <% end %>
        <div class="col s2 m1" style="padding:0">
          <ul class="right">
            <li>
              <% if user_signed_in? %>
              <a style="margin:0" href="#" data-target="notification-trigger" class="right white-text sidenav-trigger show-on-large"><i class="material-icons">notifications</i></a>
              <%end%>
            </li>
          </ul>
        </div>
        </div>
</div>
      </nav>
    </div>

    <!-- Se l'utente è loggato.. -->
    <!-- SideNav Notifiche [DESTRA]-->
    <% if user_signed_in? %>
    <ul id="notification-trigger" data-behaviour="notifications"class="sidenav notification-sidenav fixed" >
    </ul>
    <%end%>

    <!-- SideNav Menu [SINISTRA]-->
    <ul class="sidenav sidenav-sidenav" id="sidenav-trigger">
      <%if user_signed_in?%>
      <li>
        <div class="user-view">
          <div class="background green darken-3">
            <!--img src="images/office.jpg"-->
          </div>
          <a href="<%=user_path(current_user)%>">
            <% if current_user && current_user.avatar.present?%>
            <%= image_tag current_user.avatar, :class =>"circle avatar responsive-img" %>
            <% else %>
            <% if current_user && current_user.remote_avatar_url != nil%>
            <%= image_tag current_user.remote_avatar_url, :class =>"circle avatar responsive-img"%>
            <% end %>
            <% end %>
          </a>
          <a href="<%=user_path(current_user)%>"><span class="white-text name"><%=current_user.name%></span></a>
          <a href="<%=user_path(current_user)%>"><span class="white-text email"><%=current_user.email%></span></a>
        </div>
      </li>
      <%end%>
      <% if current_page?(:controller => '/home', :action => 'index') == false %>
      <li><%= link_to root_path do%>
        Home<i class="material-icons">home</i>
        <%end%></li>
      <% end %>
      <% if current_page?(root_path) == false %>
      <%end%>
      <% if user_signed_in? %>
        <% if current_page?(user_path(current_user)) == false %>
      <li><%= link_to current_user do %><i class=" material-icons" style="color: #0000008a">person</i>Profilo<%end%></li>
        <% end %>
        <li><div class="divider"></div></li>
        <li><a href="<%= new_match_path %>" ><i class=" small icon-soccer-court" style="color: #0000008a !important"></i>Organizza partita</a></li>
        <li><a href="<%= new_team_path %>" ><i class=" small icon-soccer-shoe" style="color: #0000008a !important"></i>Crea squadra</a></li>
        <li><a href="<%= new_free_match_path %>" ><i class=" small fas fa-futbol" style="color: #0000008a !important"></i>Organizza amichevole</a></li>
        <li><div class="divider"></div></li>
        <% if current_page?(user_path(current_user)) == false %>
        <li><a href="<%= edit_user_registration_path %>"><i class=" material-icons">settings</i> Impostazioni</a></li>
        <% end %>
        <li><%= link_to destroy_user_session_path, method: :delete do%>Logout<i class="material-icons">exit_to_app</i><%end%></li>
      <% else %>
        <li>
        <!--%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %-->
        <%= link_to('Login', new_user_session_path)  %>
        </li>
      <% end %>


    </ul>

    <!-- Contenuto View -->
    <div class="row">
      <%= yield %>
    </div>
    <!-- Fine View -->

    <!-- Se l'utente è loggato posso mostrare il Floating Action Button -->
    <!-- Inizio Floating Action Button -->
    <% if user_signed_in? %>
    <div class="fixed-action-btn">
      <a id="calci8_button" class="btn-floating btn-large green darken-3">
        <i class="large material-icons">add</i>
      </a>
      <ul>
        <li><a href="<%= new_match_path %>" data-tooltip="Crea Partita" class="tooltipped btn-floating white"><i class="icon-soccer-court" style="color: black !important"></i></a></li>
        <li><a href="<%= new_team_path %>" data-tooltip="Crea Squadra" class="tooltipped btn-floating white"><i class="icon-soccer-shoe" style="color: black !important"></i></a></li>
        <li><a href="<%= new_free_match_path %>" data-tooltip="Crea Amichevole" class="tooltipped btn-floating white"><i class="fas fa-futbol" style="color: black !important"></i></a></li>
      </ul>
    </div>
    <%end%>
    <!-- Se l'utente è loggato posso mostrare il Floating Action Button -->
    <!-- Inizio Floating Action Button -->

    <!-- Script per la gestione dei Toasts -->
    <script>
    <% if notice %>
    M.toast({html: '<%= notice %>'});
    <% end %>
    <% if alert %>
    M.toast({html: '<%= alert %>'});
    <% end %>
    </script>
    <!-- Fine Script Toasts -->


    <% if current_user && current_user.sign_in_count == 1 && current_page?(root_path) %>
    <!-- Script da integrare solo in caso di primo Login -->
    <script>
    var fea_elems, fea_instances, fea_tap, fea_tap_instances;
      $(document).on('turbolinks:before-cache', function() {
        fea_elems = document.querySelectorAll('.tap-target');
        fea_instances = M.Sidenav.getInstance(notification_elem);
        if (fea_instances) {
          return fea_instances.destroy();
        }
        fea_tap = document.querySelectorAll('.tap-target');
        fea_tap_instances = M.TapTarget.getInstance(fea_tap);
        if (fea_tap_instances) {
          return fea_tap_instances.destroy();
        }
      });

      $(document).on('turbolinks:load', function() {
        fea_tap = document.querySelectorAll('.tap-target');
        if(fea_tap.length != 0){
          fea_tap_instances = M.TapTarget.init(fea_tap, {});
          if (fea_tap_instances !== void 0) {
            //console.log(fea_tap_instances);
            callback = function() {
              return fea_tap_instances[0].open();
            };
            return setTimeout(callback, 2000);
          }
        }
      });
    </script>
    <% else %>
    <% end %>
  </main>

  <!-- Inizio del footer -->
  <footer class="page-footer grey darken-2">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Dribbler</h5>
          <span class="grey-text text-lighten-4">
            Quest'app è stata realizzata per il progetto universitario del laboratorio di
            "Progetto Applicazione Software e Sicurezza Informatica".
            Corso della facoltà di Ingegneria Informatica
            e automatica sostenuto dai professori Querzoni e Mecella.
          </span>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="btn-flat grey white-text text-lighten-3" href="https://github.com/lquerzoni/lassi-lab">
              Github<i class="fab fa-github right"></i>
            </a></li><br>
            <li><a class="btn-flat grey white-text text-lighten-3" href="https://gitlab.com/useless-id/lassilab">
              GitLab<i class="fab fa-gitlab right"></i></a>
            </li><br>
            <li><a class="btn-flat grey white-text text-lighten-3" href="https://piazza.com/uniroma1.it/spring2016/aaf1519aaf1520aaf1569/home">
              Piazza del corso</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2018 Stefano Latini
      <!--a class="grey-text text-lighten-4 right" href="#!">More Links</a-->
      </div>
    </div>
  <!-- Fine del footer -->
  </footer>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dribbler</title>
    <%= csrf_meta_tags %>
    <!-- Meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Links -->
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Roboto|Roboto+Mono" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/solid.css" integrity="sha384-VxweGom9fDoUf7YfLTHgO0r70LVNHP5+Oi8dcR4hbEjS8UnpRtrwTx7LpHq/MWLI" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">

    <script type="text/javascript" src="https://unpkg.com/default-passive-events"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dribbler</title>
    <%= csrf_meta_tags %>
    <!-- Meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Links -->
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Roboto|Roboto+Mono" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/solid.css" integrity="sha384-VxweGom9fDoUf7YfLTHgO0r70LVNHP5+Oi8dcR4hbEjS8UnpRtrwTx7LpHq/MWLI" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">

    <script type="text/javascript" src="https://unpkg.com/default-passive-events"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <div class="valign-wrapper green darken-3" style="width:100%;position:absolute;height:100%">
      <div class="row center-align" style="width:100%">
        <h2 class="col s12 white-text" style="font-family: 'Pacifico', cursive;font-size:2em">Dribbler</h2>
        <i class=" col s12 large  icon-soccer-court" style="color: white !important"></i>
        <a href="<%=new_user_session_path%>" class="btn-flat white-text green darken-3">entra</a>
      </div>
    </div>
  </body>
</html>